[workspace]
name = "bulk-rnaseq-analysis"
version = "0.1.0"
description = "A collection of scripts and notebooks for bulk RNA-seq data analysis, including preprocessing, differential expression analysis, and visualization."
authors = ["Payman Tohidifar <payman.tohidifar@gmail.com>"]
channels = ["conda-forge", "bioconda"] 
platforms = ["linux-64", "osx-arm64", "win-64"]

[tasks]
lab = "jupyter lab"

[dependencies]
python = "3.11.*"
jupyterlab = ">=4.3.5"
matplotlib = ">=3.10.0"
seaborn = ">=0.13.2"
numpy = ">=2.1.0"
pandas = ">=2.2.0"
scipy = ">=1.13.0"  
requests = ">=2.32.0"
ipywidgets = ">=8.1.2"
pixi-kernel = "*"
fastcluster = ">=1.3.0,<2"

[feature.ml.dependencies]
scikit-learn = ">=1.5.0"

[feature.bio.dependencies]
pydeseq2 = ">=0.5.4"
scanpy = ">=1.11.5,<2"

[feature.bio.pypi-dependencies]
pycomplexheatmap = ">=1.8.5, <2"

[environments]
default = { features = ["bio", "ml"], no-default-feature = false }
